name: Build

on: [push]
env:
  plugin-slug: imagemagick-extended

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
  
    - name: Build
      run: composer install --optimize-autoloader
  
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx webpack -p
  
    - name: Release
      run: |
        mkdir -p ${{env.plugin-slug}}
        rsync -av * ${{env.plugin-slug}} --exclude ${{env.plugin-slug}} --exclude node_modules --exclude .git --exclude .github --exclude .gitignore --exclude .editorconfig --exclude .prettierrc.js
        zip -r ${{env.plugin-slug}}.zip ${{env.plugin-slug}}
      
    - uses: actions/upload-artifact@master
      with:
        name: ${{env.plugin-slug}}.zip
        path: ${{env.plugin-slug}}.zip
            
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{env.plugin-slug}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
